=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module BuildClient
  class AddonAttachmentsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # create addon attachment
    # Attach an addon to an app
    # @param [Hash] opts the optional parameters
    # @option opts [CreateAddonAttachmentRequest] :create_addon_attachment_request 
    # @return [AddonAttachment]
    def create_addon_attachment(opts = {})
      data, _status_code, _headers = create_addon_attachment_with_http_info(opts)
      data
    end

    # create addon attachment
    # Attach an addon to an app
    # @param [Hash] opts the optional parameters
    # @option opts [CreateAddonAttachmentRequest] :create_addon_attachment_request 
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def create_addon_attachment_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddonAttachmentsApi.create_addon_attachment ...'
      end
      # resource path
      local_var_path = '/api/v1/addon-attachments'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'create_addon_attachment_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'AddonAttachment'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"AddonAttachmentsApi.create_addon_attachment",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddonAttachmentsApi#create_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # delete addon attachment
    # Detach an addon from an app
    # @param addon_attachment_id [String] Addon attachment ID
    # @param [Hash] opts the optional parameters
    # @return [AddonAttachment]
    def delete_addon_attachment(addon_attachment_id, opts = {})
      data, _status_code, _headers = delete_addon_attachment_with_http_info(addon_attachment_id, opts)
      data
    end

    # delete addon attachment
    # Detach an addon from an app
    # @param addon_attachment_id [String] Addon attachment ID
    # @param [Hash] opts the optional parameters
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def delete_addon_attachment_with_http_info(addon_attachment_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddonAttachmentsApi.delete_addon_attachment ...'
      end
      # verify the required parameter 'addon_attachment_id' is set
      if @api_client.config.client_side_validation && addon_attachment_id.nil?
        fail ArgumentError, "Missing the required parameter 'addon_attachment_id' when calling AddonAttachmentsApi.delete_addon_attachment"
      end
      # resource path
      local_var_path = '/api/v1/addon-attachments/{addon_attachment_id}'.sub('{' + 'addon_attachment_id' + '}', CGI.escape(addon_attachment_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AddonAttachment'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"AddonAttachmentsApi.delete_addon_attachment",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddonAttachmentsApi#delete_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # show addon attachment
    # Get info about an addon attachment
    # @param addon_attachment_id [String] Addon attachment ID
    # @param [Hash] opts the optional parameters
    # @return [AddonAttachment]
    def get_addon_attachment(addon_attachment_id, opts = {})
      data, _status_code, _headers = get_addon_attachment_with_http_info(addon_attachment_id, opts)
      data
    end

    # show addon attachment
    # Get info about an addon attachment
    # @param addon_attachment_id [String] Addon attachment ID
    # @param [Hash] opts the optional parameters
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def get_addon_attachment_with_http_info(addon_attachment_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddonAttachmentsApi.get_addon_attachment ...'
      end
      # verify the required parameter 'addon_attachment_id' is set
      if @api_client.config.client_side_validation && addon_attachment_id.nil?
        fail ArgumentError, "Missing the required parameter 'addon_attachment_id' when calling AddonAttachmentsApi.get_addon_attachment"
      end
      # resource path
      local_var_path = '/api/v1/addon-attachments/{addon_attachment_id}'.sub('{' + 'addon_attachment_id' + '}', CGI.escape(addon_attachment_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AddonAttachment'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"AddonAttachmentsApi.get_addon_attachment",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddonAttachmentsApi#get_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # list addon attachments
    # List all addon attachments
    # @param [Hash] opts the optional parameters
    # @return [Array<AddonAttachment>]
    def list_addon_attachments(opts = {})
      data, _status_code, _headers = list_addon_attachments_with_http_info(opts)
      data
    end

    # list addon attachments
    # List all addon attachments
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<AddonAttachment>, Integer, Hash)>] Array<AddonAttachment> data, response status code and response headers
    def list_addon_attachments_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddonAttachmentsApi.list_addon_attachments ...'
      end
      # resource path
      local_var_path = '/api/v1/addon-attachments'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<AddonAttachment>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"AddonAttachmentsApi.list_addon_attachments",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddonAttachmentsApi#list_addon_attachments\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
