# -*- encoding: utf-8 -*-

=begin
#Build.io API V1

### Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user's apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "build_client/version"

Gem::Specification.new do |s|
  s.name        = "build_client"
  s.version     = BuildClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Build.io API V1 Ruby Gem"
  s.description = "## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user's apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
