=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::AddonAttachmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddonAttachmentsApi' do
  before do
    # run before each test
    @api_instance = BuildClient::AddonAttachmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddonAttachmentsApi' do
    it 'should create an instance of AddonAttachmentsApi' do
      expect(@api_instance).to be_instance_of(BuildClient::AddonAttachmentsApi)
    end
  end

  # unit tests for create_addon_attachment
  # create addon attachment
  # Attach an addon to an app
  # @param [Hash] opts the optional parameters
  # @option opts [CreateAddonAttachmentRequest] :create_addon_attachment_request 
  # @return [AddonAttachment]
  describe 'create_addon_attachment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_addon_attachment
  # delete addon attachment
  # Detach an addon from an app
  # @param addon_attachment_id Addon attachment ID
  # @param [Hash] opts the optional parameters
  # @return [AddonAttachment]
  describe 'delete_addon_attachment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_addon_attachment
  # show addon attachment
  # Get info about an addon attachment
  # @param addon_attachment_id Addon attachment ID
  # @param [Hash] opts the optional parameters
  # @return [AddonAttachment]
  describe 'get_addon_attachment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_addon_attachments
  # list addon attachments
  # List all addon attachments
  # @param [Hash] opts the optional parameters
  # @return [Array<AddonAttachment>]
  describe 'list_addon_attachments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
