=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::AddonServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddonServicesApi' do
  before do
    # run before each test
    @api_instance = BuildClient::AddonServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddonServicesApi' do
    it 'should create an instance of AddonServicesApi' do
      expect(@api_instance).to be_instance_of(BuildClient::AddonServicesApi)
    end
  end

  # unit tests for list_addon_service_plans
  # list plans for addon service
  # List all visible plans for an addon service
  # @param name Addon service name
  # @param [Hash] opts the optional parameters
  # @return [Array<AddonPlanCatalogItem>]
  describe 'list_addon_service_plans test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_addon_services
  # list addon services
  # List all visible addon services from the catalog
  # @param [Hash] opts the optional parameters
  # @return [Array<AddonServiceCatalogItem>]
  describe 'list_addon_services test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
