=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::BuildpacksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BuildpacksApi' do
  before do
    # run before each test
    @api_instance = BuildClient::BuildpacksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BuildpacksApi' do
    it 'should create an instance of BuildpacksApi' do
      expect(@api_instance).to be_instance_of(BuildClient::BuildpacksApi)
    end
  end

  # unit tests for list_buildpacks
  # list buildpacks
  # List an app&#39;s buildpack installations in execution order
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @return [Array<BuildpackInstallation>]
  describe 'list_buildpacks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_buildpacks
  # update buildpacks
  # Replace an app&#39;s buildpack list. Order determines execution order.
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateBuildpacksRequest] :update_buildpacks_request 
  # @return [Array<BuildpackInstallation>]
  describe 'update_buildpacks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
