=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::CollaboratorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CollaboratorsApi' do
  before do
    # run before each test
    @api_instance = BuildClient::CollaboratorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollaboratorsApi' do
    it 'should create an instance of CollaboratorsApi' do
      expect(@api_instance).to be_instance_of(BuildClient::CollaboratorsApi)
    end
  end

  # unit tests for api_v1_apps_app_id_collaborators_get
  # List collaborators for an app
  # @param app_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<Collaborator>]
  describe 'api_v1_apps_app_id_collaborators_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
