=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::FormationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FormationApi' do
  before do
    # run before each test
    @api_instance = BuildClient::FormationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FormationApi' do
    it 'should create an instance of FormationApi' do
      expect(@api_instance).to be_instance_of(BuildClient::FormationApi)
    end
  end

  # unit tests for update_formation
  # batch update formation
  # Batch update process formation (Heroku-compatible)
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @option opts [FormationBatchUpdateRequest] :formation_batch_update_request 
  # @return [Hash<String, Object>]
  describe 'update_formation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
