=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BuildClient::PipelinesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PipelinesApi' do
  before do
    # run before each test
    @api_instance = BuildClient::PipelinesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PipelinesApi' do
    it 'should create an instance of PipelinesApi' do
      expect(@api_instance).to be_instance_of(BuildClient::PipelinesApi)
    end
  end

  # unit tests for get_pipeline
  # get a specific pipeline
  # Retrieves details for a specific pipeline
  # @param pipeline_id_or_name Pipeline ID or Name
  # @param [Hash] opts the optional parameters
  # @return [Pipeline]
  describe 'get_pipeline test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pipeline_apps
  # list apps in a pipeline
  # A list of applications in the pipeline.
  # @param pipeline_id_or_name Pipeline ID or Name
  # @param [Hash] opts the optional parameters
  # @return [Array<App>]
  describe 'list_pipeline_apps test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pipelines
  # list pipelines
  # Lists all pipelines accessible to the current user
  # @param [Hash] opts the optional parameters
  # @return [Array<Pipeline>]
  describe 'list_pipelines test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
