=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApiV1OidcLoginGet200ResponseSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ApiV1OidcLoginGet200ResponseSpec do
  let(:instance) { OpenapiClient::ApiV1OidcLoginGet200ResponseSpec.new }

  describe 'test an instance of ApiV1OidcLoginGet200ResponseSpec' do
    it 'should create an instance of ApiV1OidcLoginGet200ResponseSpec' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ApiV1OidcLoginGet200ResponseSpec)
    end
  end

  describe 'test attribute "interactive"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
