=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BuildClient::CreateAddonAttachmentRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BuildClient::CreateAddonAttachmentRequest do
  let(:instance) { BuildClient::CreateAddonAttachmentRequest.new }

  describe 'test an instance of CreateAddonAttachmentRequest' do
    it 'should create an instance of CreateAddonAttachmentRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BuildClient::CreateAddonAttachmentRequest)
    end
  end

  describe 'test attribute "addon"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "app"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "confirm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
