=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BuildClient::OidcLoginResponseStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BuildClient::OidcLoginResponseStatus do
  let(:instance) { BuildClient::OidcLoginResponseStatus.new }

  describe 'test an instance of OidcLoginResponseStatus' do
    it 'should create an instance of OidcLoginResponseStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BuildClient::OidcLoginResponseStatus)
    end
  end

  describe 'test attribute "expiration_timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
