=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BuildClient::PipelineEnvironmentsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BuildClient::PipelineEnvironmentsInner do
  let(:instance) { BuildClient::PipelineEnvironmentsInner.new }

  describe 'test an instance of PipelineEnvironmentsInner' do
    it 'should create an instance of PipelineEnvironmentsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BuildClient::PipelineEnvironmentsInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "kind"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ra", "ci", "ai"])
      # validator.allowable_values.each do |value|
      #   expect { instance.kind = value }.not_to raise_error
      # end
    end
  end

end
