=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

# Common files
require 'build_client/api_client'
require 'build_client/api_error'
require 'build_client/version'
require 'build_client/configuration'

# Models
require 'build_client/models/api_v1_me_get200_response'
require 'build_client/models/api_v1_namespaces_post_request'
require 'build_client/models/api_v1_oidc_login_get200_response'
require 'build_client/models/api_v1_oidc_login_get200_response_spec'
require 'build_client/models/api_v1_oidc_login_get200_response_status'
require 'build_client/models/app'
require 'build_client/models/app_buildpacks_inner'
require 'build_client/models/app_formation_value'
require 'build_client/models/app_pipeline'
require 'build_client/models/app_team'
require 'build_client/models/namespace'
require 'build_client/models/namespace_actor'
require 'build_client/models/team'

# APIs
require 'build_client/api/default_api'

module BuildClient
  class << self
    # Customize default settings for the SDK using block.
    #   BuildClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
