=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'build_client/api_client'
require 'build_client/api_error'
require 'build_client/version'
require 'build_client/configuration'

# Models
require 'build_client/models/addon'
require 'build_client/models/addon_app'
require 'build_client/models/addon_attachment'
require 'build_client/models/addon_billed_price'
require 'build_client/models/addon_plan'
require 'build_client/models/addon_service'
require 'build_client/models/app'
require 'build_client/models/app_buildpack'
require 'build_client/models/app_formation_value'
require 'build_client/models/app_pipeline'
require 'build_client/models/app_team'
require 'build_client/models/attachment_addon'
require 'build_client/models/create_addon_attachment_request'
require 'build_client/models/create_addon_request'
require 'build_client/models/create_app_request'
require 'build_client/models/create_build_request'
require 'build_client/models/create_domain_request'
require 'build_client/models/create_namespace410_response'
require 'build_client/models/create_namespace_request'
require 'build_client/models/domain'
require 'build_client/models/domain_app'
require 'build_client/models/domain_sni_endpoint'
require 'build_client/models/dyno'
require 'build_client/models/dyno_exec_request'
require 'build_client/models/dyno_exec_response'
require 'build_client/models/error_response'
require 'build_client/models/exec_output'
require 'build_client/models/me_response'
require 'build_client/models/namespace'
require 'build_client/models/namespace_actor'
require 'build_client/models/namespace_team'
require 'build_client/models/oidc_login_response'
require 'build_client/models/oidc_login_response_spec'
require 'build_client/models/oidc_login_response_status'
require 'build_client/models/pipeline'
require 'build_client/models/pipeline_environments_inner'
require 'build_client/models/pipeline_team'
require 'build_client/models/process'
require 'build_client/models/team'
require 'build_client/models/update_domain_request'
require 'build_client/models/validation_errors'

# APIs
require 'build_client/api/addon_attachments_api'
require 'build_client/api/addons_api'
require 'build_client/api/default_api'
require 'build_client/api/domains_api'
require 'build_client/api/pipelines_api'

module BuildClient
  class << self
    # Customize default settings for the SDK using block.
    #   BuildClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
