=begin
#Build.io API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module BuildClient
  class App
    attr_accessor :id

    attr_accessor :name

    attr_accessor :team

    attr_accessor :pipeline

    attr_accessor :dns_refreshed_at

    attr_accessor :builds_count

    attr_accessor :deployments_count

    attr_accessor :slugs_count

    attr_accessor :current_build_id

    attr_accessor :current_image_id

    attr_accessor :current_deployment_id

    attr_accessor :formation

    attr_accessor :stack

    attr_accessor :region

    attr_accessor :buildpacks

    attr_accessor :description

    attr_accessor :pipeline_stage

    attr_accessor :policy_allow_websockets

    attr_accessor :policy_response_timeout

    attr_accessor :policy_max_connections

    attr_accessor :policy_erosion_resistance_seconds

    attr_accessor :policy_share_process_namespace

    attr_accessor :policy_temporary_self_signed

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :deleted_at

    # Full HTTPS URL for the application
    attr_accessor :web_url

    # GitHub branch for the application
    attr_accessor :branch

    attr_accessor :environment_id

    # SSH host for running one-off dynos
    attr_accessor :ssh_host

    # SSH port for running one-off dynos
    attr_accessor :ssh_port

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'team' => :'team',
        :'pipeline' => :'pipeline',
        :'dns_refreshed_at' => :'dns_refreshed_at',
        :'builds_count' => :'builds_count',
        :'deployments_count' => :'deployments_count',
        :'slugs_count' => :'slugs_count',
        :'current_build_id' => :'current_build_id',
        :'current_image_id' => :'current_image_id',
        :'current_deployment_id' => :'current_deployment_id',
        :'formation' => :'formation',
        :'stack' => :'stack',
        :'region' => :'region',
        :'buildpacks' => :'buildpacks',
        :'description' => :'description',
        :'pipeline_stage' => :'pipeline_stage',
        :'policy_allow_websockets' => :'policy_allow_websockets',
        :'policy_response_timeout' => :'policy_response_timeout',
        :'policy_max_connections' => :'policy_max_connections',
        :'policy_erosion_resistance_seconds' => :'policy_erosion_resistance_seconds',
        :'policy_share_process_namespace' => :'policy_share_process_namespace',
        :'policy_temporary_self_signed' => :'policy_temporary_self_signed',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'deleted_at' => :'deleted_at',
        :'web_url' => :'web_url',
        :'branch' => :'branch',
        :'environment_id' => :'environment_id',
        :'ssh_host' => :'ssh_host',
        :'ssh_port' => :'ssh_port'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'team' => :'AppTeam',
        :'pipeline' => :'AppPipeline',
        :'dns_refreshed_at' => :'String',
        :'builds_count' => :'Integer',
        :'deployments_count' => :'Integer',
        :'slugs_count' => :'Integer',
        :'current_build_id' => :'String',
        :'current_image_id' => :'String',
        :'current_deployment_id' => :'String',
        :'formation' => :'Hash<String, AppFormationValue>',
        :'stack' => :'String',
        :'region' => :'String',
        :'buildpacks' => :'Array<AppBuildpack>',
        :'description' => :'String',
        :'pipeline_stage' => :'String',
        :'policy_allow_websockets' => :'Boolean',
        :'policy_response_timeout' => :'Integer',
        :'policy_max_connections' => :'Integer',
        :'policy_erosion_resistance_seconds' => :'Integer',
        :'policy_share_process_namespace' => :'Boolean',
        :'policy_temporary_self_signed' => :'Boolean',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'deleted_at' => :'String',
        :'web_url' => :'String',
        :'branch' => :'String',
        :'environment_id' => :'String',
        :'ssh_host' => :'String',
        :'ssh_port' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'pipeline',
        :'dns_refreshed_at',
        :'current_build_id',
        :'current_image_id',
        :'current_deployment_id',
        :'description',
        :'pipeline_stage',
        :'deleted_at',
        :'branch',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BuildClient::App` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BuildClient::App`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'team')
        self.team = attributes[:'team']
      else
        self.team = nil
      end

      if attributes.key?(:'pipeline')
        self.pipeline = attributes[:'pipeline']
      end

      if attributes.key?(:'dns_refreshed_at')
        self.dns_refreshed_at = attributes[:'dns_refreshed_at']
      end

      if attributes.key?(:'builds_count')
        self.builds_count = attributes[:'builds_count']
      end

      if attributes.key?(:'deployments_count')
        self.deployments_count = attributes[:'deployments_count']
      end

      if attributes.key?(:'slugs_count')
        self.slugs_count = attributes[:'slugs_count']
      end

      if attributes.key?(:'current_build_id')
        self.current_build_id = attributes[:'current_build_id']
      end

      if attributes.key?(:'current_image_id')
        self.current_image_id = attributes[:'current_image_id']
      end

      if attributes.key?(:'current_deployment_id')
        self.current_deployment_id = attributes[:'current_deployment_id']
      end

      if attributes.key?(:'formation')
        if (value = attributes[:'formation']).is_a?(Hash)
          self.formation = value
        end
      end

      if attributes.key?(:'stack')
        self.stack = attributes[:'stack']
      else
        self.stack = nil
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      else
        self.region = nil
      end

      if attributes.key?(:'buildpacks')
        if (value = attributes[:'buildpacks']).is_a?(Array)
          self.buildpacks = value
        end
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'pipeline_stage')
        self.pipeline_stage = attributes[:'pipeline_stage']
      end

      if attributes.key?(:'policy_allow_websockets')
        self.policy_allow_websockets = attributes[:'policy_allow_websockets']
      end

      if attributes.key?(:'policy_response_timeout')
        self.policy_response_timeout = attributes[:'policy_response_timeout']
      end

      if attributes.key?(:'policy_max_connections')
        self.policy_max_connections = attributes[:'policy_max_connections']
      end

      if attributes.key?(:'policy_erosion_resistance_seconds')
        self.policy_erosion_resistance_seconds = attributes[:'policy_erosion_resistance_seconds']
      end

      if attributes.key?(:'policy_share_process_namespace')
        self.policy_share_process_namespace = attributes[:'policy_share_process_namespace']
      end

      if attributes.key?(:'policy_temporary_self_signed')
        self.policy_temporary_self_signed = attributes[:'policy_temporary_self_signed']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'web_url')
        self.web_url = attributes[:'web_url']
      end

      if attributes.key?(:'branch')
        self.branch = attributes[:'branch']
      end

      if attributes.key?(:'environment_id')
        self.environment_id = attributes[:'environment_id']
      end

      if attributes.key?(:'ssh_host')
        self.ssh_host = attributes[:'ssh_host']
      else
        self.ssh_host = nil
      end

      if attributes.key?(:'ssh_port')
        self.ssh_port = attributes[:'ssh_port']
      else
        self.ssh_port = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @team.nil?
        invalid_properties.push('invalid value for "team", team cannot be nil.')
      end

      if @stack.nil?
        invalid_properties.push('invalid value for "stack", stack cannot be nil.')
      end

      if @region.nil?
        invalid_properties.push('invalid value for "region", region cannot be nil.')
      end

      if @ssh_host.nil?
        invalid_properties.push('invalid value for "ssh_host", ssh_host cannot be nil.')
      end

      if @ssh_port.nil?
        invalid_properties.push('invalid value for "ssh_port", ssh_port cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @team.nil?
      return false if @stack.nil?
      return false if @region.nil?
      return false if @ssh_host.nil?
      return false if @ssh_port.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] team Value to be assigned
    def team=(team)
      if team.nil?
        fail ArgumentError, 'team cannot be nil'
      end

      @team = team
    end

    # Custom attribute writer method with validation
    # @param [Object] stack Value to be assigned
    def stack=(stack)
      if stack.nil?
        fail ArgumentError, 'stack cannot be nil'
      end

      @stack = stack
    end

    # Custom attribute writer method with validation
    # @param [Object] region Value to be assigned
    def region=(region)
      if region.nil?
        fail ArgumentError, 'region cannot be nil'
      end

      @region = region
    end

    # Custom attribute writer method with validation
    # @param [Object] ssh_host Value to be assigned
    def ssh_host=(ssh_host)
      if ssh_host.nil?
        fail ArgumentError, 'ssh_host cannot be nil'
      end

      @ssh_host = ssh_host
    end

    # Custom attribute writer method with validation
    # @param [Object] ssh_port Value to be assigned
    def ssh_port=(ssh_port)
      if ssh_port.nil?
        fail ArgumentError, 'ssh_port cannot be nil'
      end

      @ssh_port = ssh_port
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          team == o.team &&
          pipeline == o.pipeline &&
          dns_refreshed_at == o.dns_refreshed_at &&
          builds_count == o.builds_count &&
          deployments_count == o.deployments_count &&
          slugs_count == o.slugs_count &&
          current_build_id == o.current_build_id &&
          current_image_id == o.current_image_id &&
          current_deployment_id == o.current_deployment_id &&
          formation == o.formation &&
          stack == o.stack &&
          region == o.region &&
          buildpacks == o.buildpacks &&
          description == o.description &&
          pipeline_stage == o.pipeline_stage &&
          policy_allow_websockets == o.policy_allow_websockets &&
          policy_response_timeout == o.policy_response_timeout &&
          policy_max_connections == o.policy_max_connections &&
          policy_erosion_resistance_seconds == o.policy_erosion_resistance_seconds &&
          policy_share_process_namespace == o.policy_share_process_namespace &&
          policy_temporary_self_signed == o.policy_temporary_self_signed &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          deleted_at == o.deleted_at &&
          web_url == o.web_url &&
          branch == o.branch &&
          environment_id == o.environment_id &&
          ssh_host == o.ssh_host &&
          ssh_port == o.ssh_port
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, team, pipeline, dns_refreshed_at, builds_count, deployments_count, slugs_count, current_build_id, current_image_id, current_deployment_id, formation, stack, region, buildpacks, description, pipeline_stage, policy_allow_websockets, policy_response_timeout, policy_max_connections, policy_erosion_resistance_seconds, policy_share_process_namespace, policy_temporary_self_signed, created_at, updated_at, deleted_at, web_url, branch, environment_id, ssh_host, ssh_port].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = BuildClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
